Add lxc-scripts -- Create container and config vars
coopdevs/timeoverflow-provisioning pull request #10
Opened 2018-01-08 09:52 UTC by danypr92

**What? Why?**

To improve the efficiency of developers, I add a script to quickly create a development environment isolate.
The script simplify the creation of LXC container and set host, add ssh key and install Python 2.7 to run correctly Ansible playbooks. Also mount the project folder.

Just configure your own vars and run from `timeoverflow-provisioning/`:
`./scripts/create-container.sh`

2018-01-08 20:07 UTC, enricostano commented on scripts/create-container.sh
> +app_user="ubuntu"
Since we source the same defaults from `lxc.cfg` in line `#18`, are these defaults sill needed?

2018-01-09 06:15 UTC, sauloperez requested changes

2018-01-09 06:15 UTC, sauloperez commented on scripts/create-container.sh
> +echo "Check container ${exist_container}"
I wouldn't print this message since we print one in either creation or update

2018-01-09 06:15 UTC, sauloperez commented on scripts/create-container.sh
> +count="0"
...container is running...

2018-01-09 06:15 UTC, sauloperez commented on scripts/create-container.sh
> +  echo "waiting container ip..."
Waiting for...

2018-01-09 06:15 UTC, sauloperez commented on scripts/create-container.sh
> +echo "Remove old host $host form /etc/hosts"
...$host from...

2018-01-09 06:15 UTC, sauloperez commented on scripts/create-container.sh
> +echo "Remove old $host of ~/.ssh/know_hosts"
...$host from...

2018-01-15 10:23 UTC, danypr92 commented on scripts/create-container.sh
> +# set -e
It's commented because the script stops when creates the container and not executes nexts commands

2018-01-16 07:34 UTC, sauloperez commented on scripts/create-container.sh
> +# SSH Key
can we add some spacing between these blocks as we did until this one? below here the script it's a bit harder to read.

2018-01-16 07:36 UTC, sauloperez commented on scripts/create-container.sh
> +while [ "$count" -lt 5 ] && [ -z "$ip_container" ] ; do
what about moving that magic number to a constant with a meaningful name? I think of `RETRIES`

2018-01-16 07:36 UTC, sauloperez commented on scripts/create-container.sh
> +echo "Remove old host $HOST from /etc/hosts"
s/Remove/Removing. Otherwise, it looks like I have to do it myself

2018-01-16 09:08 UTC, sauloperez approved these changes

2018-01-22 18:35 UTC, merged