Create environment file var
coopdevs/timeoverflow-provisioning pull request #150
Opened 2020-01-23 11:33 UTC by mperezv

* Create environment_file in `inventory/group_vars/all.yml`
* Set to environment_file the EnvironmentFile on sidekiq and unicorn

2020-01-23 11:47 UTC, raneq requested changes
There's a slash missing in the var definition.

And regarding the leading dash in EnvironmentFile, I don't knowit means. If it's some special systemd syntax, though, I would rather include this at  the template and not at the variable, not to mix path and syntax.

Something like `EnvironmentFile=-{{ environment_file }}` and `environment_file: "/etc/default/timeoverflow"`

However, I don't know what it means, so...

2020-01-23 12:39 UTC, danypr92 requested changes

2020-01-23 12:39 UTC, danypr92 commented on inventory/group_vars/all.yml
> +environment_file: "-etc/default/timeoverflow"
```suggestion
environment_file: "/etc/default/timeoverflow"
```

2020-01-23 12:39 UTC, danypr92 commented on inventory/group_vars/all.yml
> +environment_file: "-etc/default/timeoverflow"
We lost the previous slash: `/etc/default/timeoverflow`.

2020-01-23 12:40 UTC, mperezv commented
Cool! I'm going to change it now. Thank you @raneq

2020-01-23 12:47 UTC, mperezv commented
Done!

2020-01-23 12:54 UTC, mperezv commented
I have tested it with ansible playbook provision.yml and it only reports changes on elasticsearch.

2020-01-24 09:35 UTC, danypr92 approved these changes
Great job @mperezv! :tada:

2020-01-24 10:52 UTC, sauloperez commented
This conflicts with the changes we introduced in `master` so it'll need a rebase. Have we gone through this lecture @danypr92 and @mperezv ? :trollface:

2020-01-24 16:07 UTC, raneq approved these changes

2020-03-16 16:11 UTC, sauloperez approved these changes

2020-03-16 16:11 UTC, merged