ensure users are created before databases
coopdevs/timeoverflow-provisioning pull request #56
Opened 2019-02-14 09:32 UTC by Morantron

:raised_hands:

2019-02-14 10:37 UTC, andresgutgon approved these changes
Que facil :trollface:

2019-02-14 11:10 UTC, Morantron commented
works on my machine :tm:

2019-02-14 11:16 UTC, sauloperez approved these changes

2019-02-14 18:47 UTC, enricostano commented on roles/database/tasks/main.yml
> -    tasks_from: databases
If you remove this the whole role get executed, we just need `databases` tasks to be executed, same above for `users`.

2019-02-14 21:03 UTC, enricostano requested changes
This solution will execute the whole postgres role 3 times :scream:

2019-03-14 21:50 UTC, enricostano commented
Dealt by professionals in https://github.com/coopdevs/timeoverflow-provisioning/pull/59 :trollface:

2019-03-14 21:50 UTC, closed without merging